# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Gradle.gitlab-ci.yml

# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle

image: gradle:7-jdk11-alpine

variables:
  DRONE_TAG: "2.6.1.4" #version number

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build dashboard frontend:
  before_script:
    - cd ${CI_PROJECT_DIR}/core/src/main/resources/org/jobrunr/dashboard/frontend
    - export NODE_OPTIONS=--openssl-legacy-provider
  image: node:latest
  stage: build dashboard
  script:
    - yarn && yarn build
  artifacts:
    untracked: true
    expire_in: never
    public: false
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - .yarn-cache/
  tags:
    - docker

build:
  before_script:
    - cd ${CI_PROJECT_DIR}
  stage: build
  script: ./gradlew clean build -x test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
    needs:
      - job: build dashboard frontend

deploy:
  image: gradle:7-jdk11-alpine
  script:
    - 'gradle publish'
  only:
    - main